---
# Created by azhe on 2020-08-19 16:37

soft_name: zookeeper-docker
install_path: "/opt"

soft_version: 3.5.6

image_home: "{{install_path}}/images"
soft_file: "{{soft_name}}-{{soft_version}}.tar.gz"
soft_basic_path: "{{basic_files_path}}/{{soft_name}}/{{soft_version}}"
soft_client_port: 2181
soft_connection_port: 2888
soft_election_port: 3888
soft_home: "{{install_path}}/{{soft_name}}"
soft_profile: "/etc/profile.d/{{soft_name}}_home.sh"

installer_zookeeper_docker: install